#include<exception>
namespace A
{
	class Test
	{
		void function1()
		{
			if (true)
			{

			}
			else
			{

			}
			for (int i = 0; i < 5; i++)
			{

			}
		}
		void function2(int &a)
		{
			try {

			}
			catch (std::exception& e)
			{

			}
			while (true)
			{

			}
		}


	};
	struct ABC
	{
		int a;
	};
}
